SET GLOBAL tidb_mem_quota_query = 8 * 1024 * 1024 * 1024; 
truncate table nation;
load data local INFILE './data/nation.tbl' INTO TABLE nation FIELDS TERMINATED BY '|';
analyze table nation;
truncate table region;
load data local INFILE './data/region.tbl' INTO TABLE region FIELDS TERMINATED BY '|';
analyze table region;
truncate table part;
load data local INFILE './data/part.tbl' INTO TABLE part FIELDS TERMINATED BY '|';
analyze table part;
truncate table supplier;
load data local INFILE './data/supplier.tbl' INTO TABLE supplier FIELDS TERMINATED BY '|';
analyze table supplier;
truncate table partsupp;
load data local INFILE './data/partsupp.tbl' INTO TABLE partsupp FIELDS TERMINATED BY '|';
analyze table partsupp;
truncate table customer;
load data local INFILE './data/customer.tbl' INTO TABLE customer FIELDS TERMINATED BY '|';
analyze table customer;
truncate table orders;
load data local INFILE './data/orders.tbl' INTO TABLE orders FIELDS TERMINATED BY '|';
analyze table orders;
truncate table lineitem;
load data local INFILE './data/lineitem.tbl' INTO TABLE lineitem FIELDS TERMINATED BY '|';
analyze table lineitem;
